name: Deployment to aws prod environment
on:
  push:
    tags:
      - prod
env:
  PROJECT: ehpr
  ENV_NAME: prod
  TF_VERSION: 1.1.1

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency: ci-${github.ref}-prod
    environment:
      name: prod
    env:
      CLOUDFRONT_ID: '${{ secrets.CLOUDFRONT_ID }}'
      AWS_ACCOUNT_ID: '${{ secrets.AWS_ACCOUNT_ID }}'
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: setup node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/cache@v3
        name: Cache yarn
        with:
          path: ./.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_SA_ROLE_ARN }}
          aws-region: ca-central-1

      - name: Print Environment
        run: make print-env

      - name: Setup terraform dir
        run: make pre-build

      - name: Build web app
        run: make build-web
        env:
          NEXT_PUBLIC_KC_URL: ${{ vars.KC_URL }}
          NEXT_PUBLIC_KC_REALM: ${{ vars.KC_REALM }}
          NEXT_PUBLIC_KC_CLIENT_ID: ${{ vars.KC_CLIENT_ID }}
          NEXT_PUBLIC_KC_REDIRECT_URI: ${{ vars.KC_REDIRECT_URI }}
          NEXT_PUBLIC_KC_SECRET: ${{ secrets.KC_SECRET }}
          NEXT_PUBLIC_FEATURE_MASS_EMAIL: ${{ vars.FEATURE_MASS_EMAIL }}

      - name: Build api
        run: make build-api

      - name: Terraform config
        run: |
          make plan
          make deploy-infra
          make deploy-app
          make deploy-api
